Repository MetOffice/fab, pull requests merged in 2020-01, with the labels that each got.

#10 Skeleton production project with packaging
  .gitignore
  COPYRIGHT
  MANIFEST.in
  README.md
  setup.py
  source/fab/__init__.py
  source/fab/__main__.py
Labels: enhancement

#19 Add reference to readme about command line interface and fix the workflow
  .github/workflows/pythonpackage.yml
  README.md
Labels: bug

#14 Add very basic Fortran source sanitisation
  source/fab/__main__.py
  source/fab/language/fortran/reader.py
Labels: enhancement, help wanted
