Repository MetOffice/fab, pull requests merged in 2020-08, with the labels that each got.

#83 Config implimentation
  source/fab/builder.py
  system-tests/test.py
Labels: enhancement

#84 Sometimes the Subversion server test will fail
  unit-tests/repository_test.py
Labels: bug

#85 Add support for C source
  .github/workflows/build.yml
  setup.py
  source/fab/artifact.py
  source/fab/builder.py
  source/fab/dumper.py
  source/fab/engine.py
  source/fab/queue.py
  source/fab/tasks/c.py
  source/fab/tasks/common.py
  source/fab/tasks/fortran.py
  system-tests/CUserHeader/expected.dump.txt
  system-tests/CUserHeader/expected.exec.txt
  system-tests/CUserHeader/expected.fab.txt
  system-tests/CUserHeader/mainprog.c
  system-tests/CUserHeader/whatnumber.c
  system-tests/CUserHeader/whatnumber.h
  system-tests/MinimalC/expected.dump.txt
  system-tests/MinimalC/expected.exec.txt
  system-tests/MinimalC/expected.fab.txt
  system-tests/MinimalC/main.c
  system-tests/test.py
  unit-tests/artifact_test.py
  unit-tests/engine_test.py
  unit-tests/tasks/c_test.py
  unit-tests/tasks/common_test.py
  unit-tests/tasks/fortran_test.py
Labels: bug, enhancement
