Repository MetOffice/fab, pull requests merged in 2025-07, with the labels that each got.

#423 Subprocess testing port
  .github/workflows/build.yml
  pyproject.toml
  source/fab/artefacts.py
  source/fab/dep_tree.py
  source/fab/steps/__init__.py
  source/fab/steps/analyse.py
  source/fab/steps/archive_objects.py
  source/fab/steps/compile_c.py
  source/fab/steps/compile_fortran.py
  source/fab/steps/grab/archive.py
  source/fab/steps/link.py
  source/fab/tools/compiler.py
  source/fab/tools/compiler_wrapper.py
  source/fab/tools/flags.py
  source/fab/tools/preprocessor.py
  source/fab/tools/tool.py
  source/fab/tools/tool_repository.py
  tests/__init__.py
  tests/conftest.py
  tests/system_tests/CFortranInterop/test_CFortranInterop.py
  tests/system_tests/CUserHeader/test_CUserHeader.py
  tests/system_tests/MinimalC/test_MinimalC.py
  tests/system_tests/grab_archive/test_grab_archive.py
  tests/system_tests/incremental_fortran/test_incremental_fortran.py
  tests/system_tests/psyclone/test_psyclone_system_test.py
  tests/system_tests/zero_config/test_zero_config.py
  tests/unit_tests/steps/grab/test_svn_fcm_unit_test.py
  tests/unit_tests/steps/test_analyse.py
  tests/unit_tests/steps/test_archive_objects.py
  tests/unit_tests/steps/test_c_pragma_injector.py
  tests/unit_tests/steps/test_cleanup_prebuilds.py
  tests/unit_tests/steps/test_compile_c.py
  tests/unit_tests/steps/test_compile_fortran.py
  tests/unit_tests/steps/test_grab.py
  tests/unit_tests/steps/test_link.py
  tests/unit_tests/steps/test_link_shared_object.py
  tests/unit_tests/steps/test_preprocess.py
  tests/unit_tests/steps/test_psyclone_unit_test.py
  tests/unit_tests/steps/test_root_inc_files.py
  tests/unit_tests/steps/test_steps.py
  tests/unit_tests/test_artefacts.py
  tests/unit_tests/tools/__init__.py
  tests/unit_tests/tools/test_ar.py
  tests/unit_tests/tools/test_compiler.py
  tests/unit_tests/tools/test_compiler_wrapper.py
  tests/unit_tests/tools/test_linker.py
  tests/unit_tests/tools/test_preprocessor.py
  tests/unit_tests/tools/test_psyclone.py
  tests/unit_tests/tools/test_rsync.py
  tests/unit_tests/tools/test_shell.py
  tests/unit_tests/tools/test_tool.py
  tests/unit_tests/tools/test_tool_box.py
  tests/unit_tests/tools/test_tool_repository.py
  tests/unit_tests/tools/test_versioning.py
Labels: Release

#430 422 module path search order
  source/fab/tools/compiler.py
  tests/unit_tests/tools/test_compiler.py
  tests/unit_tests/tools/test_compiler_wrapper.py
Labels: bug, Priority, Release

#431 Fix multiple versions of the same file in archive
  source/fab/tools/ar.py
Labels: bug, Priority, Release

#450 Add build target classes to Fab
  .gitignore
  source/fab/target/base.py
  source/fab/target/zero.py
  tests/unit_tests/test_target.py
Labels: enhancement
