Repository MetOffice/fab, pull requests merged in 2025-09, with the labels that each got.

#488 Refactor documentation build process and update copyright year
  .github/CODEOWNERS
  .github/workflows/documentation.yml
  Documentation/source/conf.py
  Documentation/source/index.rst
Labels: bug, CI

#472 Fix output_fpath being cast to string in archive_objects
  source/fab/artefacts.py
  source/fab/steps/archive_objects.py
  source/fab/tools/ar.py
  tests/unit_tests/steps/test_archive_objects.py
  tests/unit_tests/test_artefacts.py
Labels: discussion

#495 Update README.md
  README.md
Labels: CI
